// Generated by CoffeeScript 1.4.0
(function() {
  var appInit, appPush, botsPush, env, envOrUrl, exec, format, getUrlFromEnv, lastArgOrDefault, prodDbUrl, urlWithoutCredentials, usage;

  format = require('util').format;

  exec = require('child_process').exec;

  prodDbUrl = "http://db.lupolibero.org/lupolibero";

  usage = function() {
    return console.log("Usage:\nhelp\nbots push [env]\napp push [env|url]\napp init [env|url]\npush [env|url]\ninit [env]");
  };

  lastArgOrDefault = function(argNum) {
    if (process.argv.length > argNum) {
      return process.argv[argNum];
    } else {
      return "default";
    }
  };

  urlWithoutCredentials = function(url) {
    return url.replace(/\/\/.*@/, '\/\/');
  };

  getUrlFromEnv = function(envOrUrl) {
    var envs;
    console.log("get url from", envOrUrl);
    if (envOrUrl[{
      0: 6
    }] === 'http://' || envOrUrl[{
      0: 7
    }] === 'https://') {
      return env_or_url;
    }
    envs = require('./.kansorc').env;
    console.log;
    if (envs && envOrUrl in envs) {
      return envs[envOrUrl].db;
    }
    throw format("invalid environment: %s", urlWithoutCredentials(envOrUrl));
  };

  botsPush = function(env) {
    return console.log("node manager.js bots push", env);
  };

  appPush = function(envOrUrl) {
    var url;
    url = getUrlFromEnv(envOrUrl);
    console.log("node manager.js app push", urlWithoutCredentials(url));
    return exec("echo toto", function(err, stdout, stderr) {
      return console.log("bla", err, stdout, stderr);
    });
  };

  appInit = function(envOrUrl) {
    var url;
    url = getUrlFromEnv(envOrUrl);
    console.log("node manager.js app init", urlWithoutCredentials(url));
    exec(format("kanso replicate %s %s", prodDbUrl, url));
    return appPush(envOrUrl);
  };

  exec("echo toto", function(err, stdout, stderr) {
    return console.log("bla", err, stdout, stderr);
  });

  if (process.argv.length === 2 || process.argv.length === 3 && process.argv[2] === "help") {
    usage();
    process.exit(0);
  }

  if (process.argv[2] === "bots") {
    if (process.argv.length === 3) {
      usage();
    }
    if (process.argv[3] === "push") {
      env = lastArgOrDefault(4);
      botsPush(env);
    }
    process.exit(0);
  }

  if (process.argv[2] === "app") {
    console.log("app");
    envOrUrl = lastArgOrDefault(4);
    if (process.argv[3] === "push") {
      appPush(envOrUrl);
    } else if (process.argv[3] === "init") {
      appInit(envOrUrl);
    }
    process.exit(0);
  }

}).call(this);
