
# install & configure latest couchdb
- include: ppa_prerequisites.yml
- apt_repository: repo='ppa:couchdb/stable'
- apt: pkg=couchdb

- name: put couchdb config file
  template: src=couchdb_conf/couchdb.override.j2
            dest=/etc/init/couchdb.override
  notify: restart couchdb

- name: put couchdb config file
  template: src=couchdb_conf/local.j2
            dest=/etc/couchdb/local.d/lupolibero.ini
  notify: restart couchdb

# TODO: recup les bons rep
- file: path={{ item }} owner=couchdb group=couchdb state=directory recurse=yes
  with_items:
    - /var/log/couchdb
    - /var/lib/couchdb

- name: restart couchdb
  service: name=couchdb state=restarted

- include: uri_prerequisites.yml

- name: create db admin
  uri: url="http://localhost:{{ couchdb_port }}/_config/admins/admin"
       body='"{{ couchdb_admin_pwd | default("admin") }}"'
       method=PUT
       status_code=200,401
  sudo: no

- name: create lupolibero db
  uri: url="http://localhost:{{ couchdb_port }}/lupolibero"
       method=PUT user=admin password={{ couchdb_admin_pwd | default("admin") }}
       force_basic_auth=yes
       status_code=201,412
  sudo: no

#- uri: url="http://localhost:{{ couchdb_port }}/_users/org.couchdb.user:role_setter"
#       body="name=role_setter&password={{ role_setter_pwd | default('role_setter') }}&roles=[]&type=user"
#       method=PUT HEADER_Content-Type="application/x-www-form-urlencoded"
#       user=admin password={{ couchdb_admin_pwd | default("admin") }}
#       force_basic_auth=yes
#  sudo: no


# download and install bots
- apt: pkg=git state=present

- name: create directory {{ bots_directory }}
  file: path={{ bots_directory }} state=directory

- copy: src=../../../../bots/{{ item }} dest={{ bots_directory }}
  with_items:
    - config.json
    - db.coffee
    - mailer.coffee
    - Model
    - notification_creator.coffee
    - role_setter.coffee
    - role_setter.conf
  tags: deploy

- copy: src=../../../../package.json dest={{ bots_directory }}
  tags: deploy

- npm: path={{ bots_directory }}/ production=yes
  tags: deploy

# cron or at for the mailer

- shell: chown -R root:couchdb {{ bots_directory }}
  tags: deploy
- shell: chmod -R go-w {{ bots_directory }}
  tags: deploy
- shell: chmod -R o-r {{ bots_directory }}/*.conf
  tags: deploy
- shell: chmod -R o-r {{ bots_directory }}/*.json
  tags: deploy
