---
- hosts: all
  sudo: yes
  tasks:
    - apt: pkg=aptitude update_cache=yes
    - apt: pkg=python-software-properties
    - apt_repository: repo='ppa:chris-lea/node.js'
    - apt: pkg=nodejs
    - apt: pkg=git
    - apt_repository: repo='ppa:couchdb/stable'
    - apt: pkg=couchdb
    - git: repo=https://github.com/lupolibero/ITS dest=./ITS
    - shell: cd ITS && npm install --production
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
