
# must install sshpass on the local machine to be able to run ansible in password mode

# launch with:
# add HOST to ssh known_host (no need to ): ssh HOST + yes + exit
# ansible-playbook -i inventory_path ansible/first_connection.yml -u USER -k
# USER must be a sudoer and would probably be root (or vagrant)

- hosts: all
  gather_facts: no
  sudo: yes
  tasks:
    - name: create a new user
      user: name=ansible state=present
            groups=sudo shell=/bin/bash


    - name: Create sudoers file backup
      command: cp -f /etc/sudoers /etc/sudoers.bak

    - name: Make sure ansible user is present in sudoers with NOPASSWD
      lineinfile: dest=/etc/sudoers state=present regexp='^ansible ALL\=' line='ansible ALL=(ALL) NOPASSWD:ALL' validate='visudo -qcf %s'

    # TODO: add password
    - name: Locally generate ssh key
      local_action: shell ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -q -N "" creates=~/.ssh/id_rsa
      sudo: no

    #- name: Add bash as ssh-agent to store the private key password
    #  local_action: ssh-agent bash
    #  sudo: no

    #- name: Add the private key to ssh-agent
    #  local_action: ssh-add ~/.ssh/id_rsa
    #  sudo: no

    - name: Add the public key to the servers authorized keys
      authorized_key: user=ansible key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
