


# create a user for the proxy
# reduce rights


- name: install coffeescript
  apt: pkg=coffeescript state=present

- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=latest

- name: create directory {{ proxy_directory }}
  file: path={{ proxy_directory }} state=directory
  tags: deploy

- copy: src=../../../../bots/{{ item }} dest={{ proxy_directory }}
  with_items:
    - config.json
    - db.coffee
    - Model
    - websocket.coffee
  tags: deploy

- copy: src=../../../../package.json dest={{ proxy_directory }}
  tags: deploy

- npm: path={{ proxy_directory }}/ production=yes
  tags: deploy

- shell: chown -R root:couchdb {{ proxy_directory }}
  tags: deploy
- shell: chmod -R go-w {{ proxy_directory }}
  tags: deploy
- shell: chmod -R o-r {{ proxy_directory }}/*.json
  tags: deploy

- shell: coffee -c {{ proxy_directory }}
  tags: deploy

# TODO create a user for the proxy
# TODO reduce rights

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false
  tags: deploy

- name: "Stop example Node.js app."
  command: forever stop {{ proxy_directory }}/websocket.js
  when: "forever_list.stdout.find('{{ proxy_directory }}/websocket.js') != -1"
  tags: deploy

- name: "Start example Node.js app."
  command: forever start {{ proxy_directory }}/websocket.js
  tags: deploy

#- template
